/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bendahara_masjid;

/**
 *
 * @author HP
 */
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class awal extends javax.swing.JPanel {

    /**
     * Creates new form awal
     */
    private JPanel mainPanel;
  public awal(JPanel panel) {
    initComponents();
    this.mainPanel = panel;
    
    this.mainPanel.setLayout(new java.awt.BorderLayout());
   
    // 🌿 Ubah warna latar belakang panel
    this.setBackground(new java.awt.Color(240, 250, 240)); // hijau muda

    // 🎨 Styling font
    jLabel2.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 26));
    jLabel1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 18));
    jLabel4.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 14));
    login.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
    tabel.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
    tabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));

    tampilkanData();
}


    
     // Method untuk mengambil dan menampilkan data gabungan
    private void tampilkanData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Tanggal");
        model.addColumn("Jenis Transaksi");
        model.addColumn("Deskripsi");
        model.addColumn("Masuk (Rp)");
        model.addColumn("Keluar (Rp)");

        try {
            // Gunakan query UNION ALL yang sudah kita rancang
            String sql = "SELECT tanggal, 'Pemasukan' AS jenis, sumber AS deskripsi, jumlah AS masuk, 0 AS keluar FROM pemasukan " +
                         "UNION ALL " +
                         "SELECT tanggal, 'Pengeluaran' AS jenis, kegiatan AS deskripsi, 0 AS masuk, jumlah AS keluar FROM pengeluaran " +
                         "ORDER BY tanggal DESC";

            Connection conn = koneksidb.getKoneksi(); // Pastikan nama kelas koneksi benar
            Statement stm = conn.createStatement();
            ResultSet res = stm.executeQuery(sql);

            while (res.next()) {
                model.addRow(new Object[]{
                    res.getString("tanggal"),
                    res.getString("jenis"),
                    res.getString("deskripsi"),
                    res.getBigDecimal("masuk"),
                    res.getBigDecimal("keluar")
                });
            }
            // Mengatur model ke JTable Anda
            tabel.setModel(model); 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat log data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        login = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(500, 400));

        jLabel1.setText("KEUANGAN MASJID AL - JANNAH");

        jLabel2.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 22)
        );
        jLabel2.setText("SELAMAT DATANG DI APLIKASI");

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        login.setText("Bendahara");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        jLabel4.setText("----------------------------------------------------------------------------------------------------------------------------------------");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(login)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(login)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
mainPanel.setLayout(new BorderLayout());

mainPanel.setBackground(new java.awt.Color(30, 30, 30)); // biar full gelap

JPanel wrapper = new JPanel(new FlowLayout(FlowLayout.CENTER, 0, 50));
wrapper.setOpaque(true);
wrapper.setBackground(new java.awt.Color(30, 30, 30)); // biar gelap semua

Login loginPanel = new Login(mainPanel);
wrapper.add(loginPanel);

mainPanel.add(wrapper, BorderLayout.CENTER);
mainPanel.revalidate();
mainPanel.repaint();
javax.swing.SwingUtilities.getWindowAncestor(mainPanel).pack();

    }//GEN-LAST:event_loginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton login;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
