/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bendahara_masjid;

/**
 *
 * @author HP
 */
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JPanel;

public class DataPemasukan extends javax.swing.JPanel {

    /**
     * Creates new form DataPemasukan
     */
    private javax.swing.JPanel mainPanel;

    public DataPemasukan(JPanel panel) {
        initComponents();
        this.mainPanel = panel;

        this.mainPanel.setLayout(new java.awt.BorderLayout());

        // 🌿 Ubah warna latar belakang panel
        this.setBackground(new java.awt.Color(240, 250, 240)); // hijau muda

        tampilkanDataPemasukan();
    }

    private void tampilkanDataPemasukan() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Tanggal");
        model.addColumn("Sumber");
        model.addColumn("Jumlah (Rp)");
        model.addColumn("Keterangan");

        try {
            String sql = "SELECT * FROM pemasukan ORDER BY tanggal DESC";
            Connection conn = koneksidb.getKoneksi(); // Pastikan nama kelas koneksi Anda benar
            Statement stm = conn.createStatement();
            ResultSet res = stm.executeQuery(sql);

            while (res.next()) {
                model.addRow(new Object[]{
                    res.getInt("id_pemasukan"),
                    res.getString("tanggal"),
                    res.getString("sumber"),
                    res.getBigDecimal("jumlah"),
                    res.getString("keterangan")
                });
            }
            // Mengatur model yang sudah diisi data ke JTable Anda
            tabelPemasukan.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data pemasukan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPemasukan = new javax.swing.JTable();
        edit = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        tabelPemasukan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelPemasukan);

        edit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        tambah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tambah.setText("Tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        Home.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Home.setText("Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        hapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("DATA PEMASUKAN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("------------------------------------------------------------------------------------------");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tambah)
                                .addGap(18, 18, 18)
                                .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(hapus, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                    .addComponent(Home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel1)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambah)
                    .addComponent(edit)
                    .addComponent(hapus))
                .addGap(28, 28, 28)
                .addComponent(Home)
                .addGap(37, 37, 37))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        // 1. Dapatkan baris yang dipilih dari tabel
        int barisTerpilih = tabelPemasukan.getSelectedRow();

        // 2. Pastikan ada baris yang dipilih
        if (barisTerpilih == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin di-edit terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 3. Ambil ID dari kolom pertama (indeks 0)
        int idUntukDiedit = (int) tabelPemasukan.getValueAt(barisTerpilih, 0);

        // 4. Pindah ke panel edit sambil mengirimkan ID
        mainPanel.removeAll();
        // Kita akan buat panel PanelEditPemasukan di langkah berikutnya
        mainPanel.add(new EditPemasukan(idUntukDiedit, mainPanel));
        mainPanel.revalidate();
        mainPanel.repaint();
    }//GEN-LAST:event_editActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.add(new Home(mainPanel));
        mainPanel.revalidate();
        mainPanel.repaint();
    }//GEN-LAST:event_HomeActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.add(new Pemasukan(mainPanel));
        mainPanel.revalidate();
        mainPanel.repaint();
    }//GEN-LAST:event_tambahActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        // 1. Dapatkan baris yang dipilih oleh pengguna dari tabel
        int barisTerpilih = tabelPemasukan.getSelectedRow();

        // 2. Pastikan ada baris yang dipilih
        if (barisTerpilih == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return; // Hentikan eksekusi jika tidak ada baris yang dipilih
        }

        // 3. Tampilkan dialog konfirmasi sebelum menghapus
        int pilihan = JOptionPane.showConfirmDialog(this,
                "Apakah Anda yakin ingin menghapus data ini?",
                "Konfirmasi Hapus",
                JOptionPane.YES_NO_OPTION);

        // 4. Lanjutkan hanya jika pengguna memilih "Yes"
        if (pilihan == JOptionPane.YES_OPTION) {
            try {
                // Ambil ID dari kolom pertama (indeks 0) pada baris yang dipilih
                int idUntukDihapus = (int) tabelPemasukan.getValueAt(barisTerpilih, 0);

                // Buat perintah SQL DELETE
                String sql = "DELETE FROM pemasukan WHERE id_pemasukan = ?";
                java.sql.Connection conn = koneksidb.getKoneksi(); // Pastikan nama kelas koneksi benar
                java.sql.PreparedStatement ps = conn.prepareStatement(sql);

                // Set ID untuk klausa WHERE
                ps.setInt(1, idUntukDihapus);

                // Eksekusi perintah delete
                ps.executeUpdate();

                // Tampilkan pesan sukses
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus.");

                // Muat ulang data di tabel untuk menampilkan perubahan
                tampilkanDataPemasukan();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_hapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Home;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelPemasukan;
    private javax.swing.JButton tambah;
    // End of variables declaration//GEN-END:variables
}
