/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bendahara_masjid;

/**
 *
 * @author ASUS
 */
import javax.swing.JOptionPane;
import javax.swing.JPanel;
public class Home extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    
    private JPanel mainPanel;
    public Home(JPanel panel) {
        initComponents();
         this.mainPanel = panel;

// 🌿 Warna latar cerah hijau muda
this.setBackground(new java.awt.Color(240, 250, 240)); // hijau pastel

// 🎨 Styling judul dan label
jLabel1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 22));  // Bendahara Masjid
jLabel2.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 24));  // Selamat Datang
jLabel3.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 16)); // Pilih menu
jLabel4.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 14)); // garis

// 🔘 Styling tombol-tombol
java.awt.Font buttonFont = new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14);

Pemasukan.setFont(buttonFont);
Pengeluaran.setFont(buttonFont);
LogData.setFont(buttonFont);

Logout.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Pemasukan = new javax.swing.JButton();
        Pengeluaran = new javax.swing.JButton();
        LogData = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel1.setText("Bendahara Masjid");

        Pemasukan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Pemasukan.setText("Catat Pemasukan");
        Pemasukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PemasukanActionPerformed(evt);
            }
        });

        Pengeluaran.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Pengeluaran.setText("Catat Pengeluaran");
        Pengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PengeluaranActionPerformed(evt);
            }
        });

        LogData.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LogData.setText("Lihat Riwayat Keuangan");
        LogData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogDataActionPerformed(evt);
            }
        });

        Logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Selamat Datang di Aplikasi");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Silakan pilih menu pengelolaan kas:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("-----------------------------------------------------------------------------------------------------");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LogData, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Pengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Pemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Logout)
                                        .addGap(62, 62, 62))))
                            .addComponent(jLabel3))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Pemasukan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pengeluaran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Logout)
                .addContainerGap(175, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LogDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogDataActionPerformed
        // TODO add your handling code here:
    mainPanel.removeAll();
    mainPanel.add(new LogData(mainPanel)); 
    mainPanel.revalidate();
    mainPanel.repaint();
    }//GEN-LAST:event_LogDataActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
          // 1. Tampilkan dialog konfirmasi
    int pilihan = JOptionPane.showConfirmDialog(
        this, 
        "Apakah Anda yakin ingin logout?", 
        "Konfirmasi Logout", 
        JOptionPane.YES_NO_OPTION);
    
    // 2. Cek jika pengguna menekan tombol "Yes"
    if (pilihan == JOptionPane.YES_OPTION) {
        // Hapus panel saat ini (Home) dari panel utama
        mainPanel.removeAll();
        
        // Tambahkan panel login yang baru
        mainPanel.add(new Login(mainPanel));
        
        // Perbarui tampilan panel utama
        mainPanel.revalidate();
        mainPanel.repaint();
    }
    }//GEN-LAST:event_LogoutActionPerformed

    private void PemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PemasukanActionPerformed
        // TODO add your handling code here:
    mainPanel.removeAll();
    mainPanel.add(new DataPemasukan(mainPanel)); 
    mainPanel.revalidate();
    mainPanel.repaint();
    }//GEN-LAST:event_PemasukanActionPerformed

    private void PengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PengeluaranActionPerformed
        // TODO add your handling code here:
    mainPanel.removeAll();
    mainPanel.add(new DataPengeluaran(mainPanel)); 
    mainPanel.revalidate();
    mainPanel.repaint();
    }//GEN-LAST:event_PengeluaranActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogData;
    private javax.swing.JButton Logout;
    private javax.swing.JButton Pemasukan;
    private javax.swing.JButton Pengeluaran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
